### ISSUE TITLE
autofix not working

### ISSUE THREAD

**Issue by bejaz-lc** [fernandrone/linelint#10] opened 2023-09-21 12:02 UTC
I'm using this action in my GitHub actions and autofix is true in .linelint.yml but this only report issues but doesn't auto fix them. I have also granted write permissions to the job in github action using permissions: contents: write. 

I'm attaching Screen Shot of the configuration below
![image](https://github.com/fernandrone/linelint/assets/132333271/4dc54b09-f540-4cbd-8314-dc3c141bd52c)

**Comment by fernandrone** [comment] 2024-07-22 22:06
Hey @bejaz-lc . First of all, sorry for not responding. I had not been actively maintaining this repository this past year and ended up missing the notification.

Not sure if my answer is useful anymore but in any case I tried to reproduce your issue but wasn't able to. I've opened a test pull request adding several empty newlines to the README file of this repository (https://github.com/fernandrone/linelint/pull/15) and here's the result https://github.com/fernandrone/linelint/actions/runs/10048996615/job/27774177785?pr=15

As can be seen from the logs, the linelinter does fix the file...

```
[EOF Rule] File "README.md" has lint errors
[EOF Rule] File "README.md" lint errors fixed
```

_However_, it does so within the GitHub Action environment. If you want to apply these changes you'd have to run to add a new step that performs a "git push", or maybe opens a pull request from there. Not sure that's something I'd recommend.

Here's the .linelint.yml configuration file used, it's pretty much like yours https://github.com/fernandrone/linelint/blob/test-action/.linelint.yml

Let me know if that's been helpful 👍🏻

**Comment by arujjval** [comment] 2024-07-24 06:05
@fernandrone thanks for responding. 

I have tried this and still, the auto fix is not working. Maybe it's because there are many files in my repo which has this error. Does this have any issue with fixing errors when there are a lot of files?

![Screenshot from 2024-07-24 11-34-38](https://github.com/user-attachments/assets/8aefec67-f405-4c64-a053-23af0387e1a5)

**Comment by fernandrone** [comment] 2024-07-26 14:22
Hi @arujjval 

The number of files should not be an issue.

Could I see your .linelint.yml file? The github action will take its configuration from there. My best guess is that there's a misconfiguration in the .linelint.yml or something else is preventing the linelint binary from interpreting it.

Also if you could share a link to the repository (if it's open source) or reproduce it in an open-source repository it'll be easier for me to help you.

Edit: also, here's the code for reading the config file (https://github.com/fernandrone/linelint/blob/test-action/linter/config.go#L42C6-L42C23). If a config file can't be found or there's an error reading it you should see a message like "No configuration file found" and the default config (no autofix) will be used.

**Comment by arujjval** [comment] 2024-07-27 04:58
@fernandrone It worked when I put `linelint@master` instead of `linelint@0.0.4`.

Also, does it support the filtering of files? I mean, I only want to run the check on changed files, not on the whole repo.

**Comment by fernandrone** [comment] 2024-08-04 21:15
Sorry, I see the issue now. The latest release is actually `linelint@0.0.6`, which includes a fix to the `autofix` property. Unfortunately since it was marked as a "pre-release" it would not show up as a GitHub Action (but `linelint@master` would would work fine as you find out).

I've updated release 0.0.6 to be a proper release and it's now showing up in the actions marketplace as intended:

![image](https://github.com/user-attachments/assets/ff94d04e-ee9f-4257-bcdf-c455aaf92d0f)

**Comment by arujjval** [comment] 2024-08-05 03:38
@fernandrone Thanks!

**Comment by fernandrone** [comment] 2024-09-14 20:38
Closing this as it's solved.

**Closed as completed by fernandrone** 2024-09-14 20:38 UTC
